trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection: 'az-serviceprincipal'

  # Web Apps Dev
  webApp_OneFichiers_Dev: 'webapp-OneFichiers-et4k'
  webApp_OneCommandes_Dev: 'webapp-OneCommandes-et4k'
  webApp_OneFidelite_Dev: 'webapp-OneFidelite-et4k'
  webApp_OneProduit_Dev: 'webapp-OneProduit-et4k'
  webApp_OneCommerceMVC_Dev: 'webapp-OneCommerceMVC-et4k'

  # Web Apps Prod
  webApp_OneFichiers_Prod: 'webapp-OneFichiers-zddl'
  webApp_OneCommandes_Prod: 'webapp-OneCommandes-zddl'
  webApp_OneFidelite_Prod: 'webapp-OneFidelite-zddl'
  webApp_OneProduit_Prod: 'webapp-OneProduit-zddl'
  webApp_OneCommerceMVC_Prod: 'webapp-OneCommerceMVC-zddl'

stages:

# BUILD

- stage: Build
  displayName: 'Build et exécution des tests'
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Restaurer les packages'
      inputs:
        command: 'restore'
        projects: '**/src/**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Génération de la solution'
      inputs:
        command: 'build'
        projects: '**/src/**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Exécution des tests unitaires'
      inputs:
        command: 'test'
        projects: '**/tests/**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration)'

    # --- PUBLICATION PAR PROJET ---
    - task: DotNetCoreCLI@2
      displayName: 'Publish OneFichiers'
      inputs:
        command: 'publish'
        projects: '**/OneFichiers.API/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/OneFichiers'

    - task: DotNetCoreCLI@2
      displayName: 'Publish OneCommandes'
      inputs:
        command: 'publish'
        projects: '**/OneCommandes.API/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/OneCommandes'

    - task: DotNetCoreCLI@2
      displayName: 'Publish OneFidelite'
      inputs:
        command: 'publish'
        projects: '**/OneFidelite.API/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/OneFidelite'

    - task: DotNetCoreCLI@2
      displayName: 'Publish OneProduit'
      inputs:
        command: 'publish'
        projects: '**/OneProduit.API/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/OneProduit'

    - task: DotNetCoreCLI@2
      displayName: 'Publish OneCommerceMVC'
      inputs:
        command: 'publish'
        projects: '**/OneCommerce.MVC/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/OneCommerceMVC'

    - task: PublishBuildArtifacts@1
      displayName: 'Publication de l’artefact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


# DEPLOY APIs DEV

- stage: DeployApisDev
  displayName: 'Déploiement APIs Dev'
  dependsOn: Build
  condition: succeeded()
  jobs:

  - deployment: Deploy_OneFichiers_Dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneFichiers_Dev)'
              package: '$(System.ArtifactsDirectory)/drop/OneFichiers/*API.zip'

  - deployment: Deploy_OneCommandes_Dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneCommandes_Dev)'
              package: '$(System.ArtifactsDirectory)/drop/OneCommandes/*API.zip'

  - deployment: Deploy_OneFidelite_Dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneFidelite_Dev)'
              package: '$(System.ArtifactsDirectory)/drop/OneFidelite/*API.zip'

  - deployment: Deploy_OneProduit_Dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneProduit_Dev)'
              package: '$(System.ArtifactsDirectory)/drop/OneProduit/*API.zip'


# DEPLOY MVC DEV

- stage: DeployMvcDev
  displayName: 'Déploiement MVC Dev'
  dependsOn: DeployApisDev
  condition: succeeded()
  jobs:
  - deployment: Deploy_MVC_Dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneCommerceMVC_Dev)'
              package: '$(System.ArtifactsDirectory)/drop/OneCommerceMVC/*MVC.zip'


# DEPLOY APIs PROD

- stage: DeployApisProd
  displayName: 'Déploiement APIs Prod'
  dependsOn: DeployMvcDev
  condition: succeeded()
  jobs:

  - deployment: Deploy_OneFichiers_Prod
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneFichiers_Prod)'
              package: '$(System.ArtifactsDirectory)/drop/OneFichiers/*API.zip'

  - deployment: Deploy_OneCommandes_Prod
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneCommandes_Prod)'
              package: '$(System.ArtifactsDirectory)/drop/OneCommandes/*API.zip'

  - deployment: Deploy_OneFidelite_Prod
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneFidelite_Prod)'
              package: '$(System.ArtifactsDirectory)/drop/OneFidelite/*API.zip'

  - deployment: Deploy_OneProduit_Prod
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneProduit_Prod)'
              package: '$(System.ArtifactsDirectory)/drop/OneProduit/*API.zip'


# DEPLOY MVC PROD

- stage: DeployMvcProd
  displayName: 'Déploiement MVC Prod'
  dependsOn: DeployApisProd
  condition: succeeded()
  jobs:
  - deployment: Deploy_MVC_Prod
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: '$(webApp_OneCommerceMVC_Prod)'
              package: '$(System.ArtifactsDirectory)/drop/OneCommerceMVC/*MVC.zip'